<?php

return [
    'title' => 'Hero: editorial 12 колонок inspector manifest',
    'generator' => [
        'name' => 'nordicblocks-scaffold',
        'managed' => true,
        'stage' => 3,
        'profile' => 'hero_like',
        'designSystemMode' => 'global-first',
        'sourceModeProfile' => 'content_item',
    ],
    'entities' => [
        'eyebrow' => [],
        'title' => [],
        'subtitle' => [],
        'body' => [],
        'primaryButton' => [],
        'media' => [],
        'mediaSurface' => [],
        'accentSurface' => [],
        'bodySurface' => [],
    ],
    'entityGroups' => [
        'content' => [
            'label' => 'Текст',
            'entities' => [
                'eyebrow',
                'title',
                'subtitle',
                'body',
            ],
        ],
        'buttons' => [
            'label' => 'Кнопки',
            'entities' => [
                'primaryButton',
            ],
        ],
        'media' => [
            'label' => 'Медиа',
            'entities' => [
                'media',
                'mediaSurface',
            ],
        ],
        'surfaces' => [
            'label' => 'Панели',
            'entities' => [
                'accentSurface',
                'bodySurface',
            ],
        ],
        'narrative' => [
            'label' => 'Текстовая панель',
            'entities' => [
                'body',
            ],
        ],
    ],
    'capabilities' => [
        'sectionBackground' => true,
        'sectionContainer' => true,
        'titleContent' => true,
        'subtitleContent' => true,
        'bodyContent' => true,
        'buttonsContent' => true,
        'mediaContent' => true,
        'eyebrowTypography' => true,
        'titleTypography' => true,
        'subtitleTypography' => true,
        'bodyTypography' => true,
        'buttonsStyle' => true,
        'mediaStyle' => true,
        'mediaSurface' => true,
        'accentSurface' => true,
        'bodySurface' => true,
        'spacingLayout' => true,
        'alignmentLayout' => true,
        'responsiveTypography' => true,
        'responsiveSpacing' => true,
        'dataBindings' => true,
    ],
    'panels' => [
        'textEyebrowContent' => [],
        'textTitleContent' => [],
        'textSubtitleContent' => [],
        'bodyContent' => [],
        'buttonsContent' => [],
        'mediaContent' => [],
        'sectionBackground' => [],
        'sectionContainer' => [],
        'eyebrowTypography' => [],
        'titleTypography' => [],
        'subtitleTypography' => [],
        'bodyTypography' => [],
        'buttonsStyle' => [],
        'mediaStyle' => [],
        'mediaSurface' => [],
        'accentSurface' => [],
        'bodySurface' => [],
        'spacingLayout' => [],
        'alignmentLayout' => [],
        'dataBindings' => [],
    ],
];
