<?php

class NordicblocksInspectorDefinitionRegistry {

    public static function getTabs() {
        return [
            ['key' => 'content', 'label' => 'Контент', 'order' => 10],
            ['key' => 'design',  'label' => 'Дизайн',  'order' => 20],
            ['key' => 'layout',  'label' => 'Макет',   'order' => 30],
            ['key' => 'data',    'label' => 'Данные',  'order' => 40],
        ];
    }

    public static function getEntities() {
        return [
            'section' => [
                'key'         => 'section',
                'label'       => 'Секция',
                'kind'        => 'surface',
                'level'       => 'block',
                'styleSlot'   => 'section',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.section',
            ],
            'header' => [
                'key'         => 'header',
                'label'       => 'Шапка секции',
                'kind'        => 'group',
                'level'       => 'block',
                'styleSlot'   => 'header',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.header',
            ],
            'eyebrow' => [
                'key'         => 'eyebrow',
                'label'       => 'Надзаголовок',
                'kind'        => 'text',
                'level'       => 'block',
                'styleSlot'   => 'eyebrow',
                'dataSlot'    => 'badge',
                'contentPath' => 'content.eyebrow',
                'designPath'  => 'design.entities.eyebrow',
            ],
            'title' => [
                'key'         => 'title',
                'label'       => 'Заголовок',
                'kind'        => 'text',
                'level'       => 'block',
                'styleSlot'   => 'title',
                'dataSlot'    => 'title',
                'contentPath' => 'content.title',
                'designPath'  => 'design.entities.title',
            ],
            'subtitle' => [
                'key'         => 'subtitle',
                'label'       => 'Подзаголовок',
                'kind'        => 'text',
                'level'       => 'block',
                'styleSlot'   => 'subtitle',
                'dataSlot'    => 'subtitle',
                'contentPath' => 'content.subtitle',
                'designPath'  => 'design.entities.subtitle',
            ],
            'meta' => [
                'key'         => 'meta',
                'label'       => 'Мета',
                'kind'        => 'text',
                'level'       => 'block',
                'styleSlot'   => 'meta',
                'dataSlot'    => 'meta',
                'contentPath' => 'content.meta',
                'designPath'  => 'design.entities.meta',
            ],
            'body' => [
                'key'         => 'body',
                'label'       => 'Основной текст',
                'kind'        => 'text',
                'level'       => 'block',
                'styleSlot'   => 'body',
                'dataSlot'    => 'body',
                'contentPath' => 'content.body',
                'designPath'  => 'design.entities.body',
            ],
            'primaryButton' => [
                'key'         => 'primaryButton',
                'label'       => 'Основная кнопка',
                'kind'        => 'button',
                'level'       => 'block',
                'styleSlot'   => 'primaryButton',
                'dataSlot'    => 'primaryButton',
                'contentPath' => 'content.primaryButton',
                'designPath'  => 'design.entities.primaryButton',
            ],
            'secondaryButton' => [
                'key'         => 'secondaryButton',
                'label'       => 'Вторичная кнопка',
                'kind'        => 'button',
                'level'       => 'block',
                'styleSlot'   => 'secondaryButton',
                'dataSlot'    => 'secondaryButton',
                'contentPath' => 'content.secondaryButton',
                'designPath'  => 'design.entities.secondaryButton',
            ],
            'tertiaryButton' => [
                'key'         => 'tertiaryButton',
                'label'       => 'Третья кнопка',
                'kind'        => 'button',
                'level'       => 'block',
                'styleSlot'   => 'tertiaryButton',
                'dataSlot'    => 'tertiaryButton',
                'contentPath' => 'content.tertiaryButton',
                'designPath'  => 'design.entities.tertiaryButton',
            ],
            'media' => [
                'key'         => 'media',
                'label'       => 'Медиа',
                'kind'        => 'media',
                'level'       => 'block',
                'styleSlot'   => 'media',
                'dataSlot'    => 'image',
                'contentPath' => 'content.media',
                'designPath'  => 'design.entities.media',
            ],
            'mediaSurface' => [
                'key'         => 'mediaSurface',
                'label'       => 'Поверхность медиа',
                'kind'        => 'surface',
                'level'       => 'block',
                'styleSlot'   => 'mediaSurface',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.mediaSurface',
            ],
            'accentSurface' => [
                'key'         => 'accentSurface',
                'label'       => 'Акцентная панель',
                'kind'        => 'surface',
                'level'       => 'block',
                'styleSlot'   => 'accentSurface',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.accentSurface',
            ],
            'bodySurface' => [
                'key'         => 'bodySurface',
                'label'       => 'Темная панель',
                'kind'        => 'surface',
                'level'       => 'block',
                'styleSlot'   => 'bodySurface',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.bodySurface',
            ],
            'items' => [
                'key'         => 'items',
                'label'       => 'Элементы',
                'kind'        => 'repeater',
                'level'       => 'block',
                'styleSlot'   => 'items',
                'dataSlot'    => 'items',
                'contentPath' => 'content.items',
                'designPath'  => 'design.entities.items',
            ],
            'viewport' => [
                'key'         => 'viewport',
                'label'       => 'Viewport слайдера',
                'kind'        => 'surface',
                'level'       => 'block',
                'styleSlot'   => 'viewport',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.viewport',
            ],
            'track' => [
                'key'         => 'track',
                'label'       => 'Трек слайдера',
                'kind'        => 'group',
                'level'       => 'block',
                'styleSlot'   => 'track',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.track',
            ],
            'slide' => [
                'key'         => 'slide',
                'label'       => 'Слайды',
                'kind'        => 'repeater',
                'level'       => 'block',
                'styleSlot'   => 'slide',
                'dataSlot'    => 'slides',
                'contentPath' => 'content.slides',
                'designPath'  => 'design.entities.slide',
            ],
            'navigation' => [
                'key'         => 'navigation',
                'label'       => 'Навигация слайдера',
                'kind'        => 'group',
                'level'       => 'block',
                'styleSlot'   => 'navigation',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.navigation',
            ],
            'prevButton' => [
                'key'         => 'prevButton',
                'label'       => 'Кнопка Назад',
                'kind'        => 'button',
                'level'       => 'block',
                'styleSlot'   => 'prevButton',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.prevButton',
            ],
            'nextButton' => [
                'key'         => 'nextButton',
                'label'       => 'Кнопка Вперед',
                'kind'        => 'button',
                'level'       => 'block',
                'styleSlot'   => 'nextButton',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.nextButton',
            ],
            'pagination' => [
                'key'         => 'pagination',
                'label'       => 'Пагинация слайдера',
                'kind'        => 'surface',
                'level'       => 'block',
                'styleSlot'   => 'pagination',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.pagination',
            ],
            'progress' => [
                'key'         => 'progress',
                'label'       => 'Прогресс слайдера',
                'kind'        => 'surface',
                'level'       => 'block',
                'styleSlot'   => 'progress',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.progress',
            ],
            'itemSurface' => [
                'key'         => 'itemSurface',
                'label'       => 'Поверхность элемента',
                'kind'        => 'surface',
                'level'       => 'item',
                'styleSlot'   => 'itemSurface',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.itemSurface',
            ],
            'itemTitle' => [
                'key'         => 'itemTitle',
                'label'       => 'Заголовок элемента',
                'kind'        => 'text',
                'level'       => 'item',
                'styleSlot'   => 'itemTitle',
                'dataSlot'    => 'items[].title',
                'contentPath' => 'content.items[].title',
                'designPath'  => 'design.entities.itemTitle',
            ],
            'itemText' => [
                'key'         => 'itemText',
                'label'       => 'Текст элемента',
                'kind'        => 'text',
                'level'       => 'item',
                'styleSlot'   => 'itemText',
                'dataSlot'    => 'items[].text',
                'contentPath' => 'content.items[].text',
                'designPath'  => 'design.entities.itemText',
            ],
            'itemLink' => [
                'key'         => 'itemLink',
                'label'       => 'CTA элемента',
                'kind'        => 'text',
                'level'       => 'item',
                'styleSlot'   => 'itemLink',
                'dataSlot'    => 'items[].link',
                'contentPath' => 'content.items[].link',
                'designPath'  => 'design.entities.itemLink',
            ],
            'slideSurface' => [
                'key'         => 'slideSurface',
                'label'       => 'Поверхность слайда',
                'kind'        => 'surface',
                'level'       => 'item',
                'styleSlot'   => 'slideSurface',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.slideSurface',
            ],
            'slideMedia' => [
                'key'         => 'slideMedia',
                'label'       => 'Медиа слайда',
                'kind'        => 'media',
                'level'       => 'item',
                'styleSlot'   => 'slideMedia',
                'dataSlot'    => 'slides[].image',
                'contentPath' => 'content.slides[].media',
                'designPath'  => 'design.entities.slideMedia',
            ],
            'slideEyebrow' => [
                'key'         => 'slideEyebrow',
                'label'       => 'Надзаголовок слайда',
                'kind'        => 'text',
                'level'       => 'item',
                'styleSlot'   => 'slideEyebrow',
                'dataSlot'    => 'slides[].eyebrow',
                'contentPath' => 'content.slides[].eyebrow',
                'designPath'  => 'design.entities.slideEyebrow',
            ],
            'slideTitle' => [
                'key'         => 'slideTitle',
                'label'       => 'Заголовок слайда',
                'kind'        => 'text',
                'level'       => 'item',
                'styleSlot'   => 'slideTitle',
                'dataSlot'    => 'slides[].title',
                'contentPath' => 'content.slides[].title',
                'designPath'  => 'design.entities.slideTitle',
            ],
            'slideText' => [
                'key'         => 'slideText',
                'label'       => 'Текст слайда',
                'kind'        => 'text',
                'level'       => 'item',
                'styleSlot'   => 'slideText',
                'dataSlot'    => 'slides[].text',
                'contentPath' => 'content.slides[].text',
                'designPath'  => 'design.entities.slideText',
            ],
            'slideMeta' => [
                'key'         => 'slideMeta',
                'label'       => 'Мета слайда',
                'kind'        => 'text',
                'level'       => 'item',
                'styleSlot'   => 'slideMeta',
                'dataSlot'    => 'slides[].meta',
                'contentPath' => 'content.slides[].meta',
                'designPath'  => 'design.entities.slideMeta',
            ],
            'slidePrimaryAction' => [
                'key'         => 'slidePrimaryAction',
                'label'       => 'Основной CTA слайда',
                'kind'        => 'button',
                'level'       => 'item',
                'styleSlot'   => 'slidePrimaryAction',
                'dataSlot'    => 'slides[].primaryAction',
                'contentPath' => 'content.slides[].primaryAction',
                'designPath'  => 'design.entities.slidePrimaryAction',
            ],
            'slideSecondaryAction' => [
                'key'         => 'slideSecondaryAction',
                'label'       => 'Вторичный CTA слайда',
                'kind'        => 'button',
                'level'       => 'item',
                'styleSlot'   => 'slideSecondaryAction',
                'dataSlot'    => 'slides[].secondaryAction',
                'contentPath' => 'content.slides[].secondaryAction',
                'designPath'  => 'design.entities.slideSecondaryAction',
            ],
            'toolbar' => [
                'key'         => 'toolbar',
                'label'       => 'Панель фильтров',
                'kind'        => 'group',
                'level'       => 'block',
                'styleSlot'   => 'toolbar',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.toolbar',
            ],
            'toolbarControls' => [
                'key'         => 'toolbarControls',
                'label'       => 'Поля фильтров',
                'kind'        => 'surface',
                'level'       => 'block',
                'styleSlot'   => 'toolbarControls',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.toolbarControls',
            ],
            'searchField' => [
                'key'         => 'searchField',
                'label'       => 'Поиск',
                'kind'        => 'text',
                'level'       => 'block',
                'styleSlot'   => 'searchField',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.searchField',
            ],
            'categoryFilter' => [
                'key'         => 'categoryFilter',
                'label'       => 'Фильтр категорий',
                'kind'        => 'text',
                'level'       => 'block',
                'styleSlot'   => 'categoryFilter',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.categoryFilter',
            ],
            'priceFilter' => [
                'key'         => 'priceFilter',
                'label'       => 'Фильтр цены',
                'kind'        => 'text',
                'level'       => 'block',
                'styleSlot'   => 'priceFilter',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.priceFilter',
            ],
            'sortControl' => [
                'key'         => 'sortControl',
                'label'       => 'Сортировка',
                'kind'        => 'text',
                'level'       => 'block',
                'styleSlot'   => 'sortControl',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.sortControl',
            ],
            'activeFilters' => [
                'key'         => 'activeFilters',
                'label'       => 'Активные фильтры',
                'kind'        => 'text',
                'level'       => 'block',
                'styleSlot'   => 'activeFilters',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.activeFilters',
            ],
            'cardBadge' => [
                'key'         => 'cardBadge',
                'label'       => 'Бейдж карточки',
                'kind'        => 'text',
                'level'       => 'item',
                'styleSlot'   => 'cardBadge',
                'dataSlot'    => 'items[].badge',
                'contentPath' => 'content.items[].badge',
                'designPath'  => 'design.entities.cardBadge',
            ],
            'cardPrice' => [
                'key'         => 'cardPrice',
                'label'       => 'Цена карточки',
                'kind'        => 'text',
                'level'       => 'item',
                'styleSlot'   => 'cardPrice',
                'dataSlot'    => 'items[].price',
                'contentPath' => 'content.items[].price',
                'designPath'  => 'design.entities.cardPrice',
            ],
            'cardPrimaryAction' => [
                'key'         => 'cardPrimaryAction',
                'label'       => 'CTA карточки',
                'kind'        => 'text',
                'level'       => 'item',
                'styleSlot'   => 'cardPrimaryAction',
                'dataSlot'    => 'items[].cta',
                'contentPath' => 'content.items[].cta',
                'designPath'  => 'design.entities.cardPrimaryAction',
            ],
            'mediaModal' => [
                'key'         => 'mediaModal',
                'label'       => 'Модальное окно',
                'kind'        => 'surface',
                'level'       => 'block',
                'styleSlot'   => 'mediaModal',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.mediaModal',
            ],
            'emptyState' => [
                'key'         => 'emptyState',
                'label'       => 'Пустое состояние',
                'kind'        => 'text',
                'level'       => 'block',
                'styleSlot'   => 'emptyState',
                'dataSlot'    => null,
                'contentPath' => null,
                'designPath'  => 'design.entities.emptyState',
            ],
        ];
    }

    public static function getEntityGroups() {
        return [
            'section' => [
                'key'      => 'section',
                'label'    => 'Секция',
                'entities' => ['section'],
            ],
            'buttons' => [
                'key'      => 'buttons',
                'label'    => 'Кнопки',
                'entities' => ['primaryButton', 'secondaryButton', 'tertiaryButton'],
            ],
            'media' => [
                'key'      => 'media',
                'label'    => 'Медиа',
                'entities' => ['media', 'mediaSurface'],
            ],
            'panels' => [
                'key'      => 'panels',
                'label'    => 'Панели',
                'entities' => ['accentSurface', 'bodySurface'],
            ],
            'meta' => [
                'key'      => 'meta',
                'label'    => 'Мета',
                'entities' => ['meta'],
            ],
            'toolbar' => [
                'key'      => 'toolbar',
                'label'    => 'Фильтры',
                'entities' => ['toolbar', 'toolbarControls', 'searchField', 'categoryFilter', 'priceFilter', 'sortControl', 'activeFilters'],
            ],
            'items' => [
                'key'      => 'items',
                'label'    => 'Элементы',
                'entities' => ['items', 'itemSurface', 'itemTitle', 'itemText', 'itemLink', 'cardBadge', 'cardPrice', 'cardPrimaryAction'],
            ],
            'sliderNavigation' => [
                'key'      => 'sliderNavigation',
                'label'    => 'Навигация слайдера',
                'entities' => ['navigation', 'prevButton', 'nextButton', 'pagination', 'progress'],
            ],
            'slides' => [
                'key'      => 'slides',
                'label'    => 'Слайды',
                'entities' => ['slide', 'slideSurface', 'slideMedia', 'slideEyebrow', 'slideTitle', 'slideText', 'slideMeta', 'slidePrimaryAction', 'slideSecondaryAction'],
            ],
            'slideActions' => [
                'key'      => 'slideActions',
                'label'    => 'CTA слайда',
                'entities' => ['slidePrimaryAction', 'slideSecondaryAction'],
            ],
        ];
    }

    public static function getCapabilities() {
        return [
            'sectionBackground'   => ['key' => 'sectionBackground', 'label' => 'Фон секции', 'tab' => 'design', 'default' => true],
            'sectionContainer'    => ['key' => 'sectionContainer', 'label' => 'Контейнер секции', 'tab' => 'design', 'default' => true],
            'titleContent'        => ['key' => 'titleContent', 'label' => 'Контент заголовка', 'tab' => 'content', 'default' => false],
            'subtitleContent'     => ['key' => 'subtitleContent', 'label' => 'Контент подзаголовка', 'tab' => 'content', 'default' => false],
            'bodyContent'         => ['key' => 'bodyContent', 'label' => 'Контент основного текста', 'tab' => 'content', 'default' => false],
            'buttonsContent'      => ['key' => 'buttonsContent', 'label' => 'Контент кнопок', 'tab' => 'content', 'default' => false],
            'mediaContent'        => ['key' => 'mediaContent', 'label' => 'Контент медиа', 'tab' => 'content', 'default' => false],
            'repeaterContent'     => ['key' => 'repeaterContent', 'label' => 'Контент повторов', 'tab' => 'content', 'default' => false],
            'hasSlides'           => ['key' => 'hasSlides', 'label' => 'Слайды', 'tab' => 'content', 'default' => false],
            'eyebrowTypography'   => ['key' => 'eyebrowTypography', 'label' => 'Типографика надзаголовка', 'tab' => 'design', 'default' => false],
            'titleTypography'     => ['key' => 'titleTypography', 'label' => 'Типографика заголовка', 'tab' => 'design', 'default' => false],
            'subtitleTypography'  => ['key' => 'subtitleTypography', 'label' => 'Типографика подзаголовка', 'tab' => 'design', 'default' => false],
            'metaTypography'      => ['key' => 'metaTypography', 'label' => 'Типографика мета', 'tab' => 'design', 'default' => false],
            'bodyTypography'      => ['key' => 'bodyTypography', 'label' => 'Типографика основного текста', 'tab' => 'design', 'default' => false],
            'buttonsStyle'        => ['key' => 'buttonsStyle', 'label' => 'Стиль кнопок', 'tab' => 'design', 'default' => false],
            'mediaStyle'          => ['key' => 'mediaStyle', 'label' => 'Стиль медиа', 'tab' => 'design', 'default' => false],
            'mediaSurface'        => ['key' => 'mediaSurface', 'label' => 'Поверхность медиа', 'tab' => 'design', 'default' => false],
            'hasSliderNavigation' => ['key' => 'hasSliderNavigation', 'label' => 'Навигация слайдера', 'tab' => 'design', 'default' => false],
            'hasSliderPagination' => ['key' => 'hasSliderPagination', 'label' => 'Пагинация слайдера', 'tab' => 'design', 'default' => false],
            'hasSliderProgress'   => ['key' => 'hasSliderProgress', 'label' => 'Прогресс слайдера', 'tab' => 'design', 'default' => false],
            'toolbarSurface'      => ['key' => 'toolbarSurface', 'label' => 'Поверхность панели фильтров', 'tab' => 'design', 'default' => false],
            'toolbarControlsSurface' => ['key' => 'toolbarControlsSurface', 'label' => 'Поверхность полей фильтров', 'tab' => 'design', 'default' => false],
            'accentSurface'       => ['key' => 'accentSurface', 'label' => 'Акцентная панель', 'tab' => 'design', 'default' => false],
            'bodySurface'         => ['key' => 'bodySurface', 'label' => 'Темная панель', 'tab' => 'design', 'default' => false],
            'itemSurface'         => ['key' => 'itemSurface', 'label' => 'Поверхность элементов', 'tab' => 'design', 'default' => false],
            'itemTypography'      => ['key' => 'itemTypography', 'label' => 'Типографика элементов', 'tab' => 'design', 'default' => false],
            'cardPriceTypography' => ['key' => 'cardPriceTypography', 'label' => 'Типографика текущей цены', 'tab' => 'design', 'default' => false],
            'spacingLayout'       => ['key' => 'spacingLayout', 'label' => 'Отступы', 'tab' => 'layout', 'default' => true],
            'alignmentLayout'     => ['key' => 'alignmentLayout', 'label' => 'Выравнивание', 'tab' => 'layout', 'default' => true],
            'hasMobileSwipe'      => ['key' => 'hasMobileSwipe', 'label' => 'Mobile swipe', 'tab' => 'layout', 'default' => false],
            'hasAutoplay'         => ['key' => 'hasAutoplay', 'label' => 'Автопрокрутка', 'tab' => 'layout', 'default' => false],
            'hasLoop'             => ['key' => 'hasLoop', 'label' => 'Loop', 'tab' => 'layout', 'default' => false],
            'responsiveTypography'=> ['key' => 'responsiveTypography', 'label' => 'Адаптивная типографика', 'tab' => 'layout', 'default' => false],
            'responsiveSpacing'   => ['key' => 'responsiveSpacing', 'label' => 'Адаптивные отступы', 'tab' => 'layout', 'default' => false],
            'cssOverlayFineTune'  => ['key' => 'cssOverlayFineTune', 'label' => 'Точная CSS-подстройка', 'tab' => 'design', 'default' => false],
            'dataBindings'        => ['key' => 'dataBindings', 'label' => 'Источник данных', 'tab' => 'data', 'default' => false],
            'repeaterBindings'    => ['key' => 'repeaterBindings', 'label' => 'Привязки коллекции', 'tab' => 'data', 'default' => false],
            'hasContentListSource'=> ['key' => 'hasContentListSource', 'label' => 'content_list источник', 'tab' => 'data', 'default' => false],
        ];
    }

    public static function getControls() {
        return [
            'textContent' => [
                'key'       => 'textContent',
                'component' => 'text-content-panel',
                'label'     => 'Текстовый контент',
            ],
            'buttonContent' => [
                'key'       => 'buttonContent',
                'component' => 'button-content-panel',
                'label'     => 'Контент кнопок',
            ],
            'mediaContent' => [
                'key'       => 'mediaContent',
                'component' => 'media-content-panel',
                'label'     => 'Контент медиа',
            ],
            'sectionBackground' => [
                'key'       => 'sectionBackground',
                'component' => 'section-background-panel',
                'label'     => 'Фон секции',
            ],
            'sectionContainer' => [
                'key'       => 'sectionContainer',
                'component' => 'section-container-panel',
                'label'     => 'Контейнер секции',
            ],
            'typographyText' => [
                'key'       => 'typographyText',
                'component' => 'typography-text-panel',
                'label'     => 'Типографика текста',
            ],
            'buttonStyle' => [
                'key'       => 'buttonStyle',
                'component' => 'button-style-panel',
                'label'     => 'Стиль кнопок',
            ],
            'mediaStyle' => [
                'key'       => 'mediaStyle',
                'component' => 'media-style-panel',
                'label'     => 'Стиль медиа',
            ],
            'surfaceStyle' => [
                'key'       => 'surfaceStyle',
                'component' => 'surface-style-panel',
                'label'     => 'Стиль поверхности',
            ],
            'spacingLayout' => [
                'key'       => 'spacingLayout',
                'component' => 'spacing-layout-panel',
                'label'     => 'Отступы',
            ],
            'alignmentLayout' => [
                'key'       => 'alignmentLayout',
                'component' => 'alignment-layout-panel',
                'label'     => 'Выравнивание',
            ],
            'dataSource' => [
                'key'       => 'dataSource',
                'component' => 'data-source-panel',
                'label'     => 'Источник данных',
            ],
            'dataCollection' => [
                'key'       => 'dataCollection',
                'component' => 'data-collection-panel',
                'label'     => 'Коллекция данных',
            ],
            'repeaterItems' => [
                'key'       => 'repeaterItems',
                'component' => 'repeater-items-panel',
                'label'     => 'Элементы списка',
            ],
            'sliderSlides' => [
                'key'       => 'sliderSlides',
                'component' => 'slider-slides-panel',
                'label'     => 'Слайды',
            ],
            'sliderSurfaceDesign' => [
                'key'       => 'sliderSurfaceDesign',
                'component' => 'slider-surface-design-panel',
                'label'     => 'Поверхности слайдера',
            ],
            'sliderMediaDesign' => [
                'key'       => 'sliderMediaDesign',
                'component' => 'slider-media-design-panel',
                'label'     => 'Медиа слайда',
            ],
            'sliderNavigationDesign' => [
                'key'       => 'sliderNavigationDesign',
                'component' => 'slider-navigation-design-panel',
                'label'     => 'Навигация слайдера',
            ],
            'sliderPaginationDesign' => [
                'key'       => 'sliderPaginationDesign',
                'component' => 'slider-pagination-design-panel',
                'label'     => 'Пагинация слайдера',
            ],
            'sliderProgressDesign' => [
                'key'       => 'sliderProgressDesign',
                'component' => 'slider-progress-design-panel',
                'label'     => 'Прогресс слайдера',
            ],
            'sliderItemTypography' => [
                'key'       => 'sliderItemTypography',
                'component' => 'slider-item-typography-panel',
                'label'     => 'Типографика слайда',
            ],
            'sliderLayout' => [
                'key'       => 'sliderLayout',
                'component' => 'slider-layout-panel',
                'label'     => 'Макет слайдера',
            ],
            'sliderMotion' => [
                'key'       => 'sliderMotion',
                'component' => 'slider-motion-panel',
                'label'     => 'Анимация и движение',
            ],
            'sliderNavigationLayout' => [
                'key'       => 'sliderNavigationLayout',
                'component' => 'slider-navigation-layout-panel',
                'label'     => 'Размещение навигации',
            ],
            'sliderDataSource' => [
                'key'       => 'sliderDataSource',
                'component' => 'slider-data-source-panel',
                'label'     => 'Источник данных слайдера',
            ],
            'sliderDataQuery' => [
                'key'       => 'sliderDataQuery',
                'component' => 'slider-data-query-panel',
                'label'     => 'Запрос и mapping слайдов',
            ],
            'sliderDataVisibility' => [
                'key'       => 'sliderDataVisibility',
                'component' => 'slider-data-visibility-panel',
                'label'     => 'Видимость данных слайда',
            ],
            'cssOverlay' => [
                'key'       => 'cssOverlay',
                'component' => 'css-overlay-panel',
                'label'     => 'Точная CSS-подстройка',
            ],
        ];
    }

    public static function getPanels() {
        return [
            ['key' => 'textEyebrowContent', 'label' => 'Надзаголовок', 'tab' => 'content', 'section' => 'text', 'group' => 'eyebrow', 'order' => 110, 'requiresCapabilities' => ['titleContent'], 'requiresEntities' => ['eyebrow'], 'entityScope' => 'eyebrow', 'control' => 'textContent', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'textTitleContent', 'label' => 'Заголовок', 'tab' => 'content', 'section' => 'text', 'group' => 'title', 'order' => 120, 'requiresCapabilities' => ['titleContent'], 'requiresEntities' => ['title'], 'entityScope' => 'title', 'control' => 'textContent', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'textSubtitleContent', 'label' => 'Подзаголовок', 'tab' => 'content', 'section' => 'text', 'group' => 'subtitle', 'order' => 130, 'requiresCapabilities' => ['subtitleContent'], 'requiresEntities' => ['subtitle'], 'entityScope' => 'subtitle', 'control' => 'textContent', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'bodyContent', 'label' => 'Основной текст', 'tab' => 'content', 'section' => 'text', 'group' => 'body', 'order' => 140, 'requiresCapabilities' => ['bodyContent'], 'requiresEntities' => ['body'], 'entityScope' => 'body', 'control' => 'textContent', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'buttonsContent', 'label' => 'Кнопки', 'tab' => 'content', 'section' => 'actions', 'group' => 'buttons', 'order' => 210, 'requiresCapabilities' => ['buttonsContent'], 'requiresAnyEntities' => ['primaryButton', 'secondaryButton', 'tertiaryButton'], 'entityScope' => 'buttons', 'control' => 'buttonContent', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'mediaContent', 'label' => 'Медиа', 'tab' => 'content', 'section' => 'media', 'group' => 'media', 'order' => 310, 'requiresCapabilities' => ['mediaContent'], 'requiresEntities' => ['media'], 'entityScope' => 'media', 'control' => 'mediaContent', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'repeaterItems', 'label' => 'Элементы', 'tab' => 'content', 'section' => 'repeaters', 'group' => 'items', 'order' => 410, 'requiresCapabilities' => ['repeaterContent'], 'requiresEntities' => ['items'], 'entityScope' => 'items', 'control' => 'repeaterItems', 'breakpointAware' => false, 'repeatable' => true],
            ['key' => 'sliderSlidesContent', 'label' => 'Слайды', 'tab' => 'content', 'section' => 'repeaters', 'group' => 'slides', 'order' => 420, 'requiresCapabilities' => ['hasSlides'], 'requiresEntities' => ['slide'], 'entityScope' => 'slides', 'control' => 'sliderSlides', 'breakpointAware' => false, 'repeatable' => true],
            ['key' => 'sectionBackground', 'label' => 'Фон секции', 'tab' => 'design', 'section' => 'section', 'group' => 'background', 'order' => 110, 'requiresCapabilities' => ['sectionBackground'], 'entityScope' => 'section', 'control' => 'sectionBackground', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'sectionContainer', 'label' => 'Контейнер', 'tab' => 'design', 'section' => 'section', 'group' => 'container', 'order' => 120, 'requiresCapabilities' => ['sectionContainer'], 'entityScope' => 'section', 'control' => 'sectionContainer', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'eyebrowTypography', 'label' => 'Надзаголовок', 'tab' => 'design', 'section' => 'typography', 'group' => 'eyebrow', 'order' => 205, 'requiresCapabilities' => ['eyebrowTypography'], 'requiresEntities' => ['eyebrow'], 'entityScope' => 'eyebrow', 'control' => 'typographyText', 'breakpointAware' => true, 'repeatable' => false],
            ['key' => 'titleTypography', 'label' => 'Заголовок', 'tab' => 'design', 'section' => 'typography', 'group' => 'title', 'order' => 210, 'requiresCapabilities' => ['titleTypography'], 'requiresEntities' => ['title'], 'entityScope' => 'title', 'control' => 'typographyText', 'breakpointAware' => true, 'repeatable' => false],
            ['key' => 'subtitleTypography', 'label' => 'Подзаголовок', 'tab' => 'design', 'section' => 'typography', 'group' => 'subtitle', 'order' => 220, 'requiresCapabilities' => ['subtitleTypography'], 'requiresEntities' => ['subtitle'], 'entityScope' => 'subtitle', 'control' => 'typographyText', 'breakpointAware' => true, 'repeatable' => false],
            ['key' => 'metaTypography', 'label' => 'Мета', 'tab' => 'design', 'section' => 'typography', 'group' => 'meta', 'order' => 225, 'requiresCapabilities' => ['metaTypography'], 'requiresEntities' => ['meta'], 'entityScope' => 'meta', 'control' => 'typographyText', 'breakpointAware' => true, 'repeatable' => false],
            ['key' => 'bodyTypography', 'label' => 'Основной текст', 'tab' => 'design', 'section' => 'typography', 'group' => 'body', 'order' => 230, 'requiresCapabilities' => ['bodyTypography'], 'requiresEntities' => ['body'], 'entityScope' => 'body', 'control' => 'typographyText', 'breakpointAware' => true, 'repeatable' => false],
            ['key' => 'titleCssOverlay', 'label' => 'Fine-tune CSS', 'tab' => 'design', 'section' => 'fineTune', 'group' => 'titleCssOverlay', 'order' => 240, 'requiresCapabilities' => ['cssOverlayFineTune'], 'requiresEntities' => ['title'], 'entityScope' => 'title', 'control' => 'cssOverlay', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'bodyCssOverlay', 'label' => 'Fine-tune CSS', 'tab' => 'design', 'section' => 'fineTune', 'group' => 'bodyCssOverlay', 'order' => 245, 'requiresCapabilities' => ['cssOverlayFineTune'], 'requiresEntities' => ['body'], 'entityScope' => 'body', 'control' => 'cssOverlay', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'buttonsStyle', 'label' => 'Кнопки', 'tab' => 'design', 'section' => 'actions', 'group' => 'buttons', 'order' => 310, 'requiresCapabilities' => ['buttonsStyle'], 'requiresAnyEntities' => ['primaryButton', 'secondaryButton', 'tertiaryButton'], 'entityScope' => 'buttons', 'control' => 'buttonStyle', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'mediaStyle', 'label' => 'Медиа', 'tab' => 'design', 'section' => 'media', 'group' => 'media', 'order' => 320, 'requiresCapabilities' => ['mediaStyle'], 'requiresEntities' => ['media'], 'entityScope' => 'media', 'control' => 'mediaStyle', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'sliderMediaDesign', 'label' => 'Медиа слайда', 'tab' => 'design', 'section' => 'media', 'group' => 'slideMedia', 'order' => 325, 'requiresCapabilities' => ['hasSlides'], 'requiresEntities' => ['slideMedia'], 'entityScope' => 'slideMedia', 'control' => 'sliderMediaDesign', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'sliderNavigationDesign', 'label' => 'Навигация', 'tab' => 'design', 'section' => 'actions', 'group' => 'sliderNavigation', 'order' => 330, 'requiresCapabilities' => ['hasSliderNavigation'], 'requiresAnyEntities' => ['prevButton', 'nextButton'], 'entityScope' => 'sliderNavigation', 'control' => 'sliderNavigationDesign', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'mediaSurface', 'label' => 'Поверхность медиа', 'tab' => 'design', 'section' => 'surfaces', 'group' => 'mediaSurface', 'order' => 410, 'requiresCapabilities' => ['mediaSurface'], 'requiresEntities' => ['mediaSurface'], 'entityScope' => 'mediaSurface', 'control' => 'surfaceStyle', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'sliderPaginationDesign', 'label' => 'Пагинация', 'tab' => 'design', 'section' => 'surfaces', 'group' => 'sliderPagination', 'order' => 411, 'requiresCapabilities' => ['hasSliderPagination'], 'requiresEntities' => ['pagination'], 'entityScope' => 'pagination', 'control' => 'sliderPaginationDesign', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'sliderProgressDesign', 'label' => 'Прогресс', 'tab' => 'design', 'section' => 'surfaces', 'group' => 'sliderProgress', 'order' => 412, 'requiresCapabilities' => ['hasSliderProgress'], 'requiresEntities' => ['progress'], 'entityScope' => 'progress', 'control' => 'sliderProgressDesign', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'toolbarSurface', 'label' => 'Панель фильтров', 'tab' => 'design', 'section' => 'surfaces', 'group' => 'toolbarSurface', 'order' => 412, 'requiresCapabilities' => ['toolbarSurface'], 'requiresEntities' => ['toolbar'], 'entityScope' => 'toolbar', 'control' => 'surfaceStyle', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'toolbarControlsSurface', 'label' => 'Поля фильтров', 'tab' => 'design', 'section' => 'surfaces', 'group' => 'toolbarControlsSurface', 'order' => 414, 'requiresCapabilities' => ['toolbarControlsSurface'], 'requiresEntities' => ['toolbarControls'], 'entityScope' => 'toolbarControls', 'control' => 'surfaceStyle', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'accentSurface', 'label' => 'Акцентная панель', 'tab' => 'design', 'section' => 'surfaces', 'group' => 'accentSurface', 'order' => 420, 'requiresCapabilities' => ['accentSurface'], 'requiresEntities' => ['accentSurface'], 'entityScope' => 'accentSurface', 'control' => 'surfaceStyle', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'bodySurface', 'label' => 'Темная панель', 'tab' => 'design', 'section' => 'surfaces', 'group' => 'bodySurface', 'order' => 430, 'requiresCapabilities' => ['bodySurface'], 'requiresEntities' => ['bodySurface'], 'entityScope' => 'bodySurface', 'control' => 'surfaceStyle', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'accentSurfaceCssOverlay', 'label' => 'Fine-tune CSS', 'tab' => 'design', 'section' => 'fineTune', 'group' => 'accentSurfaceCssOverlay', 'order' => 435, 'requiresCapabilities' => ['cssOverlayFineTune'], 'requiresEntities' => ['accentSurface'], 'entityScope' => 'accentSurface', 'control' => 'cssOverlay', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'bodySurfaceCssOverlay', 'label' => 'Fine-tune CSS', 'tab' => 'design', 'section' => 'fineTune', 'group' => 'bodySurfaceCssOverlay', 'order' => 438, 'requiresCapabilities' => ['cssOverlayFineTune'], 'requiresEntities' => ['bodySurface'], 'entityScope' => 'bodySurface', 'control' => 'cssOverlay', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'itemSurface', 'label' => 'Поверхность элементов', 'tab' => 'design', 'section' => 'surfaces', 'group' => 'itemSurface', 'order' => 440, 'requiresCapabilities' => ['itemSurface'], 'requiresEntities' => ['itemSurface'], 'entityScope' => 'itemSurface', 'control' => 'surfaceStyle', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'sliderSurfaceDesign', 'label' => 'Поверхность слайда', 'tab' => 'design', 'section' => 'surfaces', 'group' => 'slideSurface', 'order' => 442, 'requiresCapabilities' => ['hasSlides'], 'requiresEntities' => ['slideSurface'], 'entityScope' => 'slideSurface', 'control' => 'sliderSurfaceDesign', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'itemTypography', 'label' => 'Типографика элементов', 'tab' => 'design', 'section' => 'typography', 'group' => 'items', 'order' => 450, 'requiresCapabilities' => ['itemTypography'], 'requiresAnyEntities' => ['itemTitle', 'itemText'], 'entityScope' => 'items', 'control' => 'typographyText', 'breakpointAware' => true, 'repeatable' => false],
            ['key' => 'sliderItemTypography', 'label' => 'Типографика слайда', 'tab' => 'design', 'section' => 'typography', 'group' => 'slides', 'order' => 452, 'requiresCapabilities' => ['hasSlides'], 'requiresAnyEntities' => ['slideEyebrow', 'slideTitle', 'slideText', 'slideMeta'], 'entityScope' => 'slides', 'control' => 'sliderItemTypography', 'breakpointAware' => true, 'repeatable' => false],
            ['key' => 'cardPriceTypography', 'label' => 'Текущая цена', 'tab' => 'design', 'section' => 'typography', 'group' => 'cardPrice', 'order' => 455, 'requiresCapabilities' => ['cardPriceTypography'], 'requiresEntities' => ['cardPrice'], 'entityScope' => 'cardPrice', 'control' => 'typographyText', 'breakpointAware' => true, 'repeatable' => false],
            ['key' => 'spacingLayout', 'label' => 'Отступы', 'tab' => 'layout', 'section' => 'spacing', 'group' => 'spacing', 'order' => 110, 'requiresCapabilities' => ['spacingLayout'], 'entityScope' => 'section', 'control' => 'spacingLayout', 'breakpointAware' => true, 'repeatable' => false],
            ['key' => 'sliderLayout', 'label' => 'Макет слайдера', 'tab' => 'layout', 'section' => 'spacing', 'group' => 'sliderLayout', 'order' => 112, 'requiresCapabilities' => ['hasSlides'], 'requiresAnyEntities' => ['viewport', 'track'], 'entityScope' => 'viewport', 'control' => 'sliderLayout', 'breakpointAware' => true, 'repeatable' => false],
            ['key' => 'sliderMotion', 'label' => 'Движение', 'tab' => 'layout', 'section' => 'alignment', 'group' => 'sliderMotion', 'order' => 114, 'requiresCapabilities' => ['hasSlides'], 'requiresEntities' => ['track'], 'entityScope' => 'track', 'control' => 'sliderMotion', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'sliderNavigationLayout', 'label' => 'Размещение навигации', 'tab' => 'layout', 'section' => 'alignment', 'group' => 'sliderNavigation', 'order' => 116, 'requiresCapabilities' => ['hasSliderNavigation'], 'requiresAnyEntities' => ['navigation', 'prevButton', 'nextButton'], 'entityScope' => 'sliderNavigation', 'control' => 'sliderNavigationLayout', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'alignmentLayout', 'label' => 'Выравнивание', 'tab' => 'layout', 'section' => 'alignment', 'group' => 'alignment', 'order' => 120, 'requiresCapabilities' => ['alignmentLayout'], 'entityScope' => 'section', 'control' => 'alignmentLayout', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'dataBindings', 'label' => 'Источник данных', 'tab' => 'data', 'section' => 'bindings', 'group' => 'source', 'order' => 110, 'requiresCapabilities' => ['dataBindings'], 'entityScope' => 'block', 'control' => 'dataSource', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'sliderDataSource', 'label' => 'Источник данных слайдера', 'tab' => 'data', 'section' => 'bindings', 'group' => 'sliderSource', 'order' => 112, 'requiresCapabilities' => ['hasContentListSource'], 'entityScope' => 'block', 'control' => 'sliderDataSource', 'breakpointAware' => false, 'repeatable' => false],
            ['key' => 'repeaterBindings', 'label' => 'Привязки коллекции', 'tab' => 'data', 'section' => 'bindings', 'group' => 'collection', 'order' => 120, 'requiresCapabilities' => ['repeaterBindings'], 'requiresEntities' => ['items'], 'entityScope' => 'items', 'control' => 'dataCollection', 'breakpointAware' => false, 'repeatable' => true],
            ['key' => 'sliderDataQuery', 'label' => 'Запрос и mapping', 'tab' => 'data', 'section' => 'bindings', 'group' => 'sliderQuery', 'order' => 122, 'requiresCapabilities' => ['hasSlides', 'hasContentListSource'], 'requiresEntities' => ['slide'], 'entityScope' => 'slides', 'control' => 'sliderDataQuery', 'breakpointAware' => false, 'repeatable' => true],
            ['key' => 'sliderDataVisibility', 'label' => 'Видимость полей', 'tab' => 'data', 'section' => 'bindings', 'group' => 'sliderVisibility', 'order' => 124, 'requiresCapabilities' => ['hasSlides'], 'requiresAnyEntities' => ['slideMedia', 'slideMeta', 'slidePrimaryAction', 'slideSecondaryAction'], 'entityScope' => 'slides', 'control' => 'sliderDataVisibility', 'breakpointAware' => false, 'repeatable' => false],
        ];
    }

    public static function getPanelMap() {
        $map = [];

        foreach (self::getPanels() as $panel) {
            $panel_key = (string) ($panel['key'] ?? '');
            if ($panel_key === '') {
                continue;
            }

            $map[$panel_key] = $panel;
        }

        return $map;
    }
}
