<?php

return [
    'title' => 'Catalog Browser inspector manifest',
    'entities' => [
        'header' => ['label' => 'Шапка секции'],
        'title' => ['label' => 'Заголовок секции'],
        'subtitle' => ['label' => 'Подзаголовок секции'],
        'primaryButton' => ['label' => 'Ссылка секции'],
        'sectionLink' => ['label' => 'Ссылка секции'],
        'toolbar' => ['label' => 'Toolbar'],
        'searchField' => ['label' => 'Поиск'],
        'categoryFilter' => ['label' => 'Фильтр категорий'],
        'priceFilter' => ['label' => 'Фильтр цены'],
        'sortControl' => ['label' => 'Сортировка'],
        'activeFilters' => ['label' => 'Активные фильтры'],
        'items' => ['label' => 'Список карточек'],
        'itemSurface' => ['label' => 'Карточка'],
        'media' => ['label' => 'Изображение карточки'],
        'meta' => ['label' => 'Мета карточки'],
        'itemTitle' => ['label' => 'Заголовок карточки'],
        'itemText' => ['label' => 'Описание карточки'],
        'grid' => ['label' => 'Сетка'],
        'cardSurface' => ['label' => 'Карточка'],
        'cardImage' => ['label' => 'Изображение карточки'],
        'cardBadge' => ['label' => 'Badge карточки'],
        'cardCategory' => ['label' => 'Категория карточки'],
        'cardTitle' => ['label' => 'Заголовок карточки'],
        'cardExcerpt' => ['label' => 'Описание карточки'],
        'cardPrice' => ['label' => 'Цена карточки'],
        'cardPrimaryAction' => ['label' => 'CTA карточки'],
        'mediaModal' => ['label' => 'Модальное окно'],
        'emptyState' => ['label' => 'Пустое состояние'],
    ],
    'entityGroups' => [
        'header' => [
            'label' => 'Шапка',
            'entities' => ['header', 'title', 'subtitle', 'primaryButton'],
        ],
        'toolbar' => [
            'label' => 'Фильтры',
            'entities' => ['toolbar', 'searchField', 'categoryFilter', 'priceFilter', 'sortControl', 'activeFilters'],
        ],
        'cards' => [
            'label' => 'Карточки',
            'entities' => ['items', 'itemSurface', 'media', 'meta', 'itemTitle', 'itemText', 'cardBadge', 'cardPrice', 'cardPrimaryAction'],
        ],
    ],
    'capabilities' => [
        'sectionBackground' => true,
        'sectionContainer' => true,
        'titleContent' => true,
        'subtitleContent' => true,
        'buttonsContent' => true,
        'repeaterContent' => true,
        'titleTypography' => true,
        'subtitleTypography' => true,
        'mediaStyle' => true,
        'itemSurface' => true,
        'itemTypography' => true,
        'spacingLayout' => true,
        'alignmentLayout' => true,
        'responsiveTypography' => true,
        'responsiveSpacing' => true,
        'dataBindings' => true,
        'repeaterBindings' => true,
    ],
    'panels' => [
        'textTitleContent' => ['label' => 'Заголовок секции'],
        'textSubtitleContent' => ['label' => 'Подзаголовок секции'],
        'buttonsContent' => ['label' => 'Ссылка секции'],
        'repeaterItems' => ['label' => 'Карточки'],
        'sectionBackground' => [],
        'sectionContainer' => [],
        'titleTypography' => ['label' => 'Заголовок секции'],
        'subtitleTypography' => ['label' => 'Подзаголовок секции'],
        'mediaStyle' => ['label' => 'Изображение карточки'],
        'itemSurface' => ['label' => 'Карточка'],
        'itemTypography' => ['label' => 'Типографика карточки'],
        'spacingLayout' => ['label' => 'Сетка и отступы'],
        'alignmentLayout' => ['label' => 'Компоновка'],
        'dataBindings' => ['label' => 'Источник данных'],
        'repeaterBindings' => ['label' => 'Поля карточек'],
    ],
];