<?php

return [
    'title' => 'Компактная бенто-лента inspector manifest',
    'generator' => [
        'name' => 'nordicblocks-scaffold',
        'managed' => true,
        'stage' => 3,
        'profile' => 'card_collection',
        'designSystemMode' => 'global-first',
        'sourceModeProfile' => 'content_list',
    ],
    'entities' => [
        'section' => ['label' => 'Секция'],
        'header' => ['label' => 'Шапка секции'],
        'title' => ['label' => 'Заголовок секции'],
        'subtitle' => ['label' => 'Описание секции'],
        'primaryButton' => ['label' => 'Ссылка секции'],
        'items' => ['label' => 'Карточки'],
        'itemSurface' => ['label' => 'Карточка'],
        'media' => ['label' => 'Изображение карточки'],
        'itemTitle' => ['label' => 'Заголовок карточки'],
        'itemText' => ['label' => 'Анонс карточки'],
        'itemLink' => ['label' => 'CTA карточки'],
        'meta' => ['label' => 'Мета карточки'],
    ],
    'entityGroups' => [
        'header' => [
            'label' => 'Шапка секции',
            'entities' => [
                'header',
                'title',
                'subtitle',
                'primaryButton',
            ],
        ],
        'items' => [
            'label' => 'Карточки',
            'entities' => [
                'items',
                'itemSurface',
                'media',
                'itemTitle',
                'itemText',
                'itemLink',
                'meta',
            ],
        ],
    ],
    'capabilities' => [
        'sectionBackground' => true,
        'sectionContainer' => true,
        'titleContent' => true,
        'subtitleContent' => true,
        'buttonsContent' => true,
        'repeaterContent' => true,
        'titleTypography' => true,
        'subtitleTypography' => true,
        'metaTypography' => true,
        'mediaStyle' => true,
        'itemSurface' => true,
        'itemTypography' => true,
        'spacingLayout' => true,
        'alignmentLayout' => true,
        'responsiveTypography' => true,
        'responsiveSpacing' => true,
        'dataBindings' => true,
        'repeaterBindings' => true,
    ],
    'panels' => [
        'textTitleContent' => ['label' => 'Заголовок секции'],
        'textSubtitleContent' => ['label' => 'Описание секции'],
        'buttonsContent' => ['label' => 'Ссылка секции'],
        'repeaterItems' => ['label' => 'Карточки'],
        'sectionBackground' => [],
        'sectionContainer' => [],
        'titleTypography' => ['label' => 'Заголовок секции'],
        'subtitleTypography' => ['label' => 'Описание секции'],
        'metaTypography' => ['label' => 'Мета карточки'],
        'mediaStyle' => ['label' => 'Изображение карточки'],
        'itemSurface' => ['label' => 'Карточка'],
        'itemTypography' => ['label' => 'Заголовок и анонс'],
        'spacingLayout' => ['label' => 'Сетка и отступы'],
        'alignmentLayout' => ['label' => 'Компоновка'],
        'dataBindings' => ['label' => 'Источник данных'],
        'repeaterBindings' => ['label' => 'Поля карточек'],
    ],
];
