<?php

    /* Generated by nordicblocks-scaffold stage 3. */

$nb_cards_slider_contract = (isset($block_contract) && is_array($block_contract) && ((string) ($block_contract['meta']['blockType'] ?? '') === 'cards_slider'))
    ? $block_contract
    : [];

if (!function_exists('nb_cards_slider_visible')) {
    function nb_cards_slider_visible($value, $default = true) {
        if ($value === null || $value === '') {
            return (bool) $default;
        }

        if (is_bool($value)) {
            return $value;
        }

        return !in_array(strtolower((string) $value), ['0', 'false', 'off', 'no'], true);
    }
}

$nb_cards_slider_content = is_array($nb_cards_slider_contract['content'] ?? null) ? $nb_cards_slider_contract['content'] : [];
$nb_cards_slider_design = is_array($nb_cards_slider_contract['design']['entities'] ?? null) ? $nb_cards_slider_contract['design']['entities'] : [];
$nb_cards_slider_title_visible = nb_cards_slider_visible($nb_cards_slider_design['title']['visible'] ?? true, true);
$nb_cards_slider_subtitle_visible = nb_cards_slider_visible($nb_cards_slider_design['subtitle']['visible'] ?? true, true);
$nb_cards_slider_title = (string) ($nb_cards_slider_content['title'] ?? 'Карточки-слайдер');
$nb_cards_slider_subtitle = (string) ($nb_cards_slider_content['subtitle'] ?? 'Подзаголовок блока');
?>
<section class="nb-section nb-cards-slider">
    <div class="nb-container">
        <?php if ($nb_cards_slider_title_visible && $nb_cards_slider_title !== '') { ?>
            <h2 class="nb-cards-slider__title"><?php echo htmlspecialchars($nb_cards_slider_title, ENT_QUOTES, 'UTF-8'); ?></h2>
        <?php } ?>
        <?php if ($nb_cards_slider_subtitle_visible && $nb_cards_slider_subtitle !== '') { ?>
            <div class="nb-cards-slider__subtitle"><?php echo nl2br(htmlspecialchars($nb_cards_slider_subtitle, ENT_QUOTES, 'UTF-8')); ?></div>
        <?php } ?>
    </div>
</section>
