INSERT INTO `{#}controllers` (`title`, `name`, `is_enabled`, `options`, `author`, `url`, `version`, `is_backend`)
VALUES ('Инстайлер', 'instyler', 1, '', 'InstantSoft', 'http://www.instantsoft.ru', '2.0.0', 1);

DROP TABLE IF EXISTS `{#}instyler_images`;
CREATE TABLE `{#}instyler_images` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `path` varchar(1024) DEFAULT NULL,
  `is_pattern` tinyint(4) unsigned DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `premade` (`is_pattern`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `{#}instyler_styles`;
CREATE TABLE IF NOT EXISTS `{#}instyler_styles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) DEFAULT NULL,
  `path` varchar(1024) DEFAULT NULL,
  `styles` text,
  `scope` tinyint(3) unsigned DEFAULT NULL,
  `mask_pos` text,
  `mask_neg` text,
  `is_enabled` tinyint(3) unsigned DEFAULT '1',
  `is_important` tinyint(3) unsigned DEFAULT NULL,
  `width` int(11) DEFAULT NULL,
  `ordering` int(10) unsigned DEFAULT NULL,
  `custom` text,
  PRIMARY KEY (`id`),
  KEY `is_enabled` (`is_enabled`),
  KEY `position` (`ordering`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `{#}instyler_images` (`id`, `title`, `path`, `is_pattern`) VALUES
(1, '45degreee_fabric', 'instyler/45degreee_fabric.png', 1),
(2, 'asanoha-400px', 'instyler/asanoha-400px.png', 1),
(3, 'asfalt', 'instyler/asfalt.png', 1),
(4, 'assault', 'instyler/assault.png', 1),
(5, 'bedge_grunge', 'instyler/bedge_grunge.png', 1),
(6, 'binding_dark', 'instyler/binding_dark.png', 1),
(7, 'binding_light', 'instyler/binding_light.png', 1),
(8, 'black_denim', 'instyler/black_denim.png', 1),
(9, 'black_linen_v2', 'instyler/black_linen_v2.png', 1),
(10, 'black_mamba', 'instyler/black_mamba.png', 1),
(11, 'blackorchid', 'instyler/blackorchid.png', 1),
(12, 'broken_noise', 'instyler/broken_noise.png', 1),
(13, 'burried', 'instyler/burried.png', 1),
(14, 'cardboard_flat', 'instyler/cardboard_flat.png', 1),
(15, 'cardboard', 'instyler/cardboard.png', 1),
(16, 'cartographer', 'instyler/cartographer.png', 1),
(17, 'cheap_diagonal_fabric', 'instyler/cheap_diagonal_fabric.png', 1),
(18, 'clean_textile', 'instyler/clean_textile.png', 1),
(19, 'concrete_seamless', 'instyler/concrete_seamless.png', 1),
(20, 'concrete_wall_2', 'instyler/concrete_wall_2.png', 1),
(21, 'concrete_wall_3', 'instyler/concrete_wall_3.png', 1),
(22, 'confectionary', 'instyler/confectionary.png', 1),
(23, 'congruent_outline', 'instyler/congruent_outline.png', 1),
(24, 'congruent_pentagon', 'instyler/congruent_pentagon.png', 1),
(25, 'connect', 'instyler/connect.png', 1),
(26, 'contemporary_china_2', 'instyler/contemporary_china_2.png', 1),
(27, 'contemporary_china', 'instyler/contemporary_china.png', 1),
(28, 'cork_1', 'instyler/cork_1.png', 1),
(29, 'creampaper', 'instyler/creampaper.png', 1),
(30, 'cream_pixels', 'instyler/cream_pixels.png', 1),
(31, 'crisp_paper_ruffles', 'instyler/crisp_paper_ruffles.png', 1),
(32, 'crissXcross', 'instyler/crissXcross.png', 1),
(33, 'cross_scratches', 'instyler/cross_scratches.png', 1),
(34, 'crossword', 'instyler/crossword.png', 1),
(35, 'darkdenim3', 'instyler/darkdenim3.png', 1),
(36, 'dark_leather', 'instyler/dark_leather.png', 1),
(37, 'dark_mosaic', 'instyler/dark_mosaic.png', 1),
(38, 'dark_Tire', 'instyler/dark_Tire.png', 1),
(39, 'dark_wall', 'instyler/dark_wall.png', 1),
(40, 'dark_wood', 'instyler/dark_wood.png', 1),
(41, 'darth_stripe', 'instyler/darth_stripe.png', 1),
(42, 'debut_dark', 'instyler/debut_dark.png', 1),
(43, 'debut_light', 'instyler/debut_light.png', 1),
(44, 'denim', 'instyler/denim.png', 1),
(45, 'diagmonds', 'instyler/diagmonds.png', 1),
(46, 'diagonal_striped_brick', 'instyler/diagonal_striped_brick.png', 1),
(47, 'diamond_upholstery', 'instyler/diamond_upholstery.png', 1),
(48, 'dirty_old_shirt', 'instyler/dirty_old_shirt.png', 1),
(49, 'dust', 'instyler/dust.png', 1),
(50, 'egg_shell', 'instyler/egg_shell.png', 1),
(51, 'eight_horns', 'instyler/eight_horns.png', 1),
(52, 'exclusive_paper', 'instyler/exclusive_paper.png', 1),
(53, 'extra_clean_paper', 'instyler/extra_clean_paper.png', 1),
(54, 'fabric_1', 'instyler/fabric_1.png', 1),
(55, 'fabric_of_squares_gray', 'instyler/fabric_of_squares_gray.png', 1),
(56, 'fabric_plaid', 'instyler/fabric_plaid.png', 1),
(57, 'farmer', 'instyler/farmer.png', 1),
(58, 'felt', 'instyler/felt.png', 1),
(59, 'foggy_birds', 'instyler/foggy_birds.png', 1),
(60, 'food', 'instyler/food.png', 1),
(61, 'footer_lodyas', 'instyler/footer_lodyas.png', 1),
(62, 'frenchstucco', 'instyler/frenchstucco.png', 1),
(63, 'fresh_snow', 'instyler/fresh_snow.png', 1),
(64, 'furley_bg', 'instyler/furley_bg.png', 1),
(65, 'geometry2', 'instyler/geometry2.png', 1),
(66, 'geometry', 'instyler/geometry.png', 1),
(67, 'giftly', 'instyler/giftly.png', 1),
(68, 'gplaypattern', 'instyler/gplaypattern.png', 1),
(69, 'gradient_squares', 'instyler/gradient_squares.png', 1),
(70, 'gray_jean', 'instyler/gray_jean.png', 1),
(71, 'gray_sand', 'instyler/gray_sand.png', 1),
(72, 'green_cup', 'instyler/green_cup.png', 1),
(73, 'green_dust_scratch', 'instyler/green_dust_scratch.png', 1),
(74, 'greyfloral', 'instyler/greyfloral.png', 1),
(75, 'grey', 'instyler/grey.png', 1),
(76, 'grey_wash_wall', 'instyler/grey_wash_wall.png', 1),
(77, 'greyzz', 'instyler/greyzz.png', 1),
(78, 'grid', 'instyler/grid.png', 1),
(79, 'grilled', 'instyler/grilled.png', 1),
(80, 'groovepaper', 'instyler/groovepaper.png', 1),
(81, 'halftone', 'instyler/halftone.png', 1),
(82, 'hexellence', 'instyler/hexellence.png', 1),
(83, 'honey_im_subtle', 'instyler/honey_im_subtle.png', 1),
(84, 'husk', 'instyler/husk.png', 1),
(85, 'ice_age', 'instyler/ice_age.png', 1),
(86, 'ignasi_pattern_s', 'instyler/ignasi_pattern_s.png', 1),
(87, 'inflicted', 'instyler/inflicted.png', 1),
(88, 'irongrip', 'instyler/irongrip.png', 1),
(89, 'kindajean', 'instyler/kindajean.png', 1),
(90, 'knitting250px', 'instyler/knitting250px.png', 1),
(91, 'large_leather', 'instyler/large_leather.png', 1),
(92, 'leather_1', 'instyler/leather_1.png', 1),
(93, 'lghtmesh', 'instyler/lghtmesh.png', 1),
(94, 'light_alu', 'instyler/light_alu.png', 1),
(95, 'light_grey', 'instyler/light_grey.png', 1),
(96, 'light_noise_diagonal', 'instyler/light_noise_diagonal.png', 1),
(97, 'lightpaperfibers', 'instyler/lightpaperfibers.png', 1),
(98, 'light_toast', 'instyler/light_toast.png', 1),
(99, 'light_wool', 'instyler/light_wool.png', 1),
(100, 'lined_paper', 'instyler/lined_paper.png', 1),
(101, 'linedpaper', 'instyler/linedpaper.png', 1),
(102, 'linen', 'instyler/linen.png', 1),
(103, 'low_contrast_linen', 'instyler/low_contrast_linen.png', 1),
(104, 'mirrored_squares', 'instyler/mirrored_squares.png', 1),
(105, 'mochaGrunge', 'instyler/mochaGrunge.png', 1),
(106, 'mooning', 'instyler/mooning.png', 1),
(107, 'nasty_fabric', 'instyler/nasty_fabric.png', 1),
(108, 'natural_paper', 'instyler/natural_paper.png', 1),
(109, 'navy_blue', 'instyler/navy_blue.png', 1),
(110, 'nice_snow', 'instyler/nice_snow.png', 1),
(111, 'noise_pattern_with_crosslines', 'instyler/noise_pattern_with_crosslines.png', 1),
(112, 'noisy_grid', 'instyler/noisy_grid.png', 1),
(113, 'noisy_net', 'instyler/noisy_net.png', 1),
(114, 'noisy', 'instyler/noisy.png', 1),
(115, 'notebook', 'instyler/notebook.png', 1),
(116, 'old_map', 'instyler/old_map.png', 1),
(117, 'old_mathematics', 'instyler/old_mathematics.png', 1),
(118, 'old_moon', 'instyler/old_moon.png', 1),
(119, 'old_wall', 'instyler/old_wall.png', 1),
(120, 'paisley', 'instyler/paisley.png', 1),
(121, 'paper_1', 'instyler/paper_1.png', 1),
(122, 'paper_2', 'instyler/paper_2.png', 1),
(123, 'paper_3', 'instyler/paper_3.png', 1),
(124, 'paper_fibers', 'instyler/paper_fibers.png', 1),
(125, 'paper', 'instyler/paper.png', 1),
(126, 'perforated_white_leather', 'instyler/perforated_white_leather.png', 1),
(127, 'photography', 'instyler/photography.png', 1),
(128, 'pink_rice', 'instyler/pink_rice.png', 1),
(129, 'pinstriped_suit', 'instyler/pinstriped_suit.png', 1),
(130, 'polonez_car', 'instyler/polonez_car.png', 1),
(131, 'pool_table', 'instyler/pool_table.png', 1),
(132, 'purty_wood', 'instyler/purty_wood.png', 1),
(133, 'pw_pattern', 'instyler/pw_pattern.png', 1),
(134, 'ravenna', 'instyler/ravenna.png', 1),
(135, 'rebel', 'instyler/rebel.png', 1),
(136, 'redox_01', 'instyler/redox_01.png', 1),
(137, 'redox_02', 'instyler/redox_02.png', 1),
(138, 'restaurant_icons', 'instyler/restaurant_icons.png', 1),
(139, 'restaurant', 'instyler/restaurant.png', 1),
(140, 'retina_dust', 'instyler/retina_dust.png', 1),
(141, 'retina_wood', 'instyler/retina_wood.png', 1),
(142, 'ricepaper2', 'instyler/ricepaper2.png', 1),
(143, 'ricepaper', 'instyler/ricepaper.png', 1),
(144, 'ricepaper_v3', 'instyler/ricepaper_v3.png', 1),
(145, 'rip_jobs', 'instyler/rip_jobs.png', 1),
(146, 'robots', 'instyler/robots.png', 1),
(147, 'rockywall', 'instyler/rockywall.png', 1),
(148, 'roughcloth', 'instyler/roughcloth.png', 1),
(149, 'rough_diagonal', 'instyler/rough_diagonal.png', 1),
(150, 'sandpaper', 'instyler/sandpaper.png', 1),
(151, 'sativa', 'instyler/sativa.png', 1),
(152, 'sayagata-400px', 'instyler/sayagata-400px.png', 1),
(153, 'school', 'instyler/school.png', 1),
(154, 'scribble_light', 'instyler/scribble_light.png', 1),
(155, 'seamless_paper_texture', 'instyler/seamless_paper_texture.png', 1),
(156, 'shattered', 'instyler/shattered.png', 1),
(157, 'skewed_print', 'instyler/skewed_print.png', 1),
(158, 'skin_side_up', 'instyler/skin_side_up.png', 1),
(159, 'skulls', 'instyler/skulls.png', 1),
(160, 'smooth_wall', 'instyler/smooth_wall.png', 1),
(161, 'snow', 'instyler/snow.png', 1),
(162, 'soft_wallpaper', 'instyler/soft_wallpaper.png', 1),
(163, 'solid', 'instyler/solid.png', 1),
(164, 'squairy_light', 'instyler/squairy_light.png', 1),
(165, 'square_bg', 'instyler/square_bg.png', 1),
(166, 'squared_metal', 'instyler/squared_metal.png', 1),
(167, 'stardust', 'instyler/stardust.png', 1),
(168, 'stitched_wool', 'instyler/stitched_wool.png', 1),
(169, 'strange_bullseyes', 'instyler/strange_bullseyes.png', 1),
(170, 'stressed_linen', 'instyler/stressed_linen.png', 1),
(171, 'stucco', 'instyler/stucco.png', 1),
(172, 'subtle_grunge', 'instyler/subtle_grunge.png', 1),
(173, 'subtle_orange_emboss', 'instyler/subtle_orange_emboss.png', 1),
(174, 'subtle_white_feathers', 'instyler/subtle_white_feathers.png', 1),
(175, 'swirl_pattern', 'instyler/swirl_pattern.png', 1),
(176, 'swirl', 'instyler/swirl.png', 1),
(177, 'symphony', 'instyler/symphony.png', 1),
(178, 'tex2res1', 'instyler/tex2res1.png', 1),
(179, 'tex2res2', 'instyler/tex2res2.png', 1),
(180, 'tex2res3', 'instyler/tex2res3.png', 1),
(181, 'tex2res4', 'instyler/tex2res4.png', 1),
(182, 'tex2res5', 'instyler/tex2res5.png', 1),
(183, 'textured_paper', 'instyler/textured_paper.png', 1),
(184, 'textured_stripes', 'instyler/textured_stripes.png', 1),
(185, 'texturetastic_gray', 'instyler/texturetastic_gray.png', 1),
(186, 'ticks', 'instyler/ticks.png', 1),
(187, 'tileable_wood_texture', 'instyler/tileable_wood_texture.png', 1),
(188, 'tree_bark', 'instyler/tree_bark.png', 1),
(189, 'tweed', 'instyler/tweed.png', 1),
(190, 'twinkle_twinkle', 'instyler/twinkle_twinkle.png', 1),
(191, 'txture', 'instyler/txture.png', 1),
(192, 'type', 'instyler/type.png', 1),
(193, 'upfeathers', 'instyler/upfeathers.png', 1),
(194, 'vertical_cloth', 'instyler/vertical_cloth.png', 1),
(195, 'vintage_speckles', 'instyler/vintage_speckles.png', 1),
(196, 'wall4', 'instyler/wall4.png', 1),
(197, 'weather', 'instyler/weather.png', 1),
(198, 'wet_snow', 'instyler/wet_snow.png', 1),
(199, 'whitediamond', 'instyler/whitediamond.png', 1),
(200, 'white_leather', 'instyler/white_leather.png', 1),
(201, 'white_paperboard', 'instyler/white_paperboard.png', 1),
(202, 'white_plaster', 'instyler/white_plaster.png', 1),
(203, 'white_sand', 'instyler/white_sand.png', 1),
(204, 'white_tiles', 'instyler/white_tiles.png', 1),
(205, 'white_wall2', 'instyler/white_wall2.png', 1),
(206, 'white_wall_hash', 'instyler/white_wall_hash.png', 1),
(207, 'white_wall', 'instyler/white_wall.png', 1),
(208, 'whitey', 'instyler/whitey.png', 1),
(209, 'wild_flowers', 'instyler/wild_flowers.png', 1),
(210, 'wild_oliva', 'instyler/wild_oliva.png', 1),
(211, 'witewall_3', 'instyler/witewall_3.png', 1),
(212, 'wood_1', 'instyler/wood_1.png', 1),
(213, 'wood_pattern', 'instyler/wood_pattern.png', 1),
(214, 'worn_dots', 'instyler/worn_dots.png', 1),
(215, 'xv', 'instyler/xv.png', 1),
(216, 'zwartevilt', 'instyler/zwartevilt.png', 1);
