<?php

return [
    'title' => 'Карточки-слайдер inspector manifest',
    'generator' => [
        'name' => 'nordicblocks-scaffold',
        'managed' => true,
        'stage' => 3,
        'profile' => 'slider_cards',
        'designSystemMode' => 'global-first',
        'sourceModeProfile' => 'content_list',
    ],
    'entities' => [
        'title' => [],
        'subtitle' => [],
        'primaryButton' => [],
        'viewport' => [],
        'track' => [],
        'slide' => [],
        'slideSurface' => [],
        'slideMedia' => [],
        'slideEyebrow' => [],
        'slideTitle' => [],
        'slideText' => [],
        'slideMeta' => [],
        'slidePrimaryAction' => [],
        'slideSecondaryAction' => [],
        'navigation' => [],
        'prevButton' => [],
        'nextButton' => [],
        'pagination' => [],
        'progress' => [],
    ],
    'entityGroups' => [
        'buttons' => [
            'label' => 'Кнопки',
            'entities' => [
                'primaryButton',
            ],
        ],
        'sliderNavigation' => [
            'label' => 'Навигация слайдера',
            'entities' => [
                'navigation',
                'prevButton',
                'nextButton',
                'pagination',
                'progress',
            ],
        ],
        'slides' => [
            'label' => 'Слайды',
            'entities' => [
                'slide',
                'slideSurface',
                'slideMedia',
                'slideEyebrow',
                'slideTitle',
                'slideText',
                'slideMeta',
                'slidePrimaryAction',
                'slideSecondaryAction',
            ],
        ],
        'slideActions' => [
            'label' => 'CTA слайда',
            'entities' => [
                'slidePrimaryAction',
                'slideSecondaryAction',
            ],
        ],
    ],
    'capabilities' => [
        'sectionBackground' => true,
        'sectionContainer' => true,
        'titleContent' => true,
        'subtitleContent' => true,
        'buttonsContent' => true,
        'titleTypography' => true,
        'subtitleTypography' => true,
        'buttonsStyle' => true,
        'spacingLayout' => true,
        'responsiveTypography' => true,
        'responsiveSpacing' => true,
        'hasSlides' => true,
        'hasSliderNavigation' => true,
        'hasSliderPagination' => true,
        'hasSliderProgress' => true,
        'hasMobileSwipe' => true,
        'hasAutoplay' => true,
        'hasLoop' => true,
        'hasContentListSource' => true,
    ],
    'panels' => [
        'textTitleContent' => [],
        'textSubtitleContent' => [],
        'buttonsContent' => [],
        'sliderSlidesContent' => [],
        'sectionBackground' => [],
        'sectionContainer' => [],
        'titleTypography' => [],
        'subtitleTypography' => [],
        'buttonsStyle' => [],
        'sliderItemTypography' => [],
        'sliderMediaDesign' => [],
        'sliderSurfaceDesign' => [],
        'sliderNavigationDesign' => [],
        'sliderPaginationDesign' => [],
        'sliderProgressDesign' => [],
        'sliderLayout' => [],
        'sliderMotion' => [],
        'sliderNavigationLayout' => [],
        'sliderDataSource' => [],
        'sliderDataQuery' => [],
        'sliderDataVisibility' => [],
    ],
];
