<?php

return [
    'title' => 'Swiss Grid inspector manifest',
    'entities' => [
        'section' => ['label' => 'Секция'],
        'header' => ['label' => 'Шапка секции'],
        'title' => ['label' => 'Заголовок секции'],
        'subtitle' => ['label' => 'Подзаголовок секции'],
        'items' => ['label' => 'Карточки'],
        'itemSurface' => ['label' => 'Карточка'],
        'media' => ['label' => 'Медиа карточки'],
        'meta' => ['label' => 'Метка карточки'],
        'itemTitle' => ['label' => 'Заголовок карточки'],
        'itemText' => ['label' => 'Текст карточки'],
        'itemLink' => ['label' => 'CTA карточки'],
    ],
    'entityGroups' => [
        'header' => [
            'label' => 'Шапка секции',
            'entities' => ['header', 'title', 'subtitle'],
        ],
        'items' => [
            'label' => 'Карточки',
            'entities' => ['items', 'itemSurface', 'media', 'meta', 'itemTitle', 'itemText', 'itemLink'],
        ],
    ],
    'capabilities' => [
        'sectionBackground' => true,
        'sectionContainer' => true,
        'titleContent' => true,
        'subtitleContent' => true,
        'repeaterContent' => true,
        'titleTypography' => true,
        'subtitleTypography' => true,
        'metaTypography' => true,
        'mediaStyle' => true,
        'itemSurface' => true,
        'itemTypography' => true,
        'spacingLayout' => true,
        'alignmentLayout' => true,
        'responsiveTypography' => true,
        'responsiveSpacing' => true,
        'dataBindings' => true,
        'repeaterBindings' => true,
    ],
    'panels' => [
        'textTitleContent' => ['label' => 'Заголовок секции'],
        'textSubtitleContent' => ['label' => 'Подзаголовок секции'],
        'repeaterItems' => ['label' => 'Карточки'],
        'sectionBackground' => [],
        'sectionContainer' => [],
        'titleTypography' => ['label' => 'Заголовок секции'],
        'subtitleTypography' => ['label' => 'Подзаголовок секции'],
        'metaTypography' => ['label' => 'Метка карточки'],
        'mediaStyle' => ['label' => 'Медиа карточки'],
        'itemSurface' => ['label' => 'Карточка'],
        'itemTypography' => ['label' => 'Заголовок и текст карточки'],
        'spacingLayout' => ['label' => 'Сетка и отступы'],
        'alignmentLayout' => ['label' => 'Компоновка'],
        'dataBindings' => ['label' => 'Источник данных'],
        'repeaterBindings' => ['label' => 'Поля карточек'],
    ],
];