/**
 * @fileoverview Cron job scaffolding tool for InstantCMS
 * Generates cron controller, manifest, and language files
 */

import { normalizeAddonName, type ScaffoldResult } from '../types/scaffold';

/**
 * Cron schedule configuration
 * All fields follow standard crontab format
 */
interface CronSchedule {
  /** Minute (0-59, * for any) */
  minute?: string;
  /** Hour (0-23, * for any) */
  hour?: string;
  /** Day of month (1-31, * for any) */
  day?: string;
  /** Month (1-12, * for any) */
  month?: string;
  /** Day of week (0-6, * for any) */
  day_of_week?: string;
}

/**
 * Single cron task definition
 */
interface CronTask {
  /** Unique task identifier */
  name: string;
  /** Cron schedule expression */
  schedule: CronSchedule;
  /** Human-readable description */
  description?: string;
  /** Action method name to call */
  action: string;
}

/**
 * Options for cron job generation
 */
interface ScaffoldCronOptions {
  /** System name of the addon */
  addon_name: string;
  /** List of cron tasks to generate */
  tasks: CronTask[];
  /** Additional configuration options */
  options?: {
    /** Enable lock file to prevent concurrent runs */
    use_lock_file?: boolean;
    /** Enable execution logging */
    log_execution?: boolean;
  };
}

/**
 * Formats a CronSchedule object into a crontab string
 */
function formatSchedule(schedule: CronSchedule): string {
  const parts = [
    schedule.minute ?? '*',
    schedule.hour ?? '*',
    schedule.day ?? '*',
    schedule.month ?? '*',
    schedule.day_of_week ?? '*',
  ];
  return parts.join(' ');
}

/**
 * Generates the main cron controller file
 */
function generateCronMain(
  name: string,
  Name: string,
  tasks: CronTask[],
  options?: ScaffoldCronOptions['options']
): string {
  const useLock = options?.use_lock_file ?? true;
  const logExecution = options?.log_execution ?? true;

  const taskCases = tasks
    .map(t => {
      return `        case '${t.name}':
            ${t.action}();
            break;`;
    })
    .join('\n');

  return `<?php
// InstantCMS 2. ${name}/cron.php
// Generated by InstantCMS MCP Server

define('PATH', dirname(__DIR__));
define('DS', DIRECTORY_SEPARATOR);

// Загрузка ядра
require_once PATH . '/core/bootstrap.php';

    ${
      useLock
        ? `
// Блокировка от повторного запуска
\\$${name}_lock_file = cmsConfig::get('cache_path') . '/${name}_cron.lock';

function ${name}_is_locked() {
    global \\$${name}_lock_file;
    if (!file_exists(\\$${name}_lock_file)) {
        return false;
    }
    $stat = stat(\\$${name}_lock_file);
    if (time() - $stat['mtime'] > 3600) {
        unlink(\\$${name}_lock_file);
        return false;
    }
    return true;
}

function ${name}_lock() {
    global \\$${name}_lock_file;
    touch(\\$${name}_lock_file);
}

function ${name}_unlock() {
    global \\$${name}_lock_file;
    if (file_exists(\\$${name}_lock_file)) {
        unlink(\\$${name}_lock_file);
    }
}

if (${name}_is_locked()) {
    die('Cron already running or locked');
}
${name}_lock();
`
        : ''
    }

${
  logExecution
    ? `
// Логирование
\\$${name}_log_file = cmsConfig::get('root_path') . '/cache/logs/${name}.log';
function ${name}_log($message) {
    global \\$${name}_log_file;
    $dir = dirname(\\$${name}_log_file);
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    file_put_contents(\\$${name}_log_file, date('Y-m-d H:i:s') . ' - ' . $message . PHP_EOL, FILE_APPEND);
}

${name}_log('Cron started');
`
    : ''
}

try {
    $task = $_SERVER['argv'][1] ?? 'all';

    switch ($task) {
${taskCases}
        default:
            // Выполняем все задачи
            ${tasks.map(t => `${t.action}();`).join('\n            ')}
            break;
    }

    ${logExecution ? `${name}_log('Cron completed successfully');` : ''}
} catch (Exception $e) {
    ${logExecution ? `${name}_log('Error: ' . $e->getMessage());` : ''}
    echo 'Error: ' . $e->getMessage() . PHP_EOL;
    exit(1);
}

${
  useLock
    ? `
${name}_unlock();
`
    : ''
}
`;
}

/**
 * Generates the manifest.xml with task definitions
 */
function generateManifest(name: string, Name: string, tasks: CronTask[]): string {
  const taskElements = tasks
    .map(t => {
      return `    <task name="${t.name}" schedule="${formatSchedule(t.schedule)}" action="${t.action}" ${t.description ? `description="${t.description}"` : ''} />`;
    })
    .join('\n');

  return `<?xml version="1.0"?>
<manifest>
    <name>${Name}</name>
    <description>${Name} component cron jobs</description>
    <version>1.0.0</version>
    <tasks>
${taskElements}
    </tasks>
</manifest>
`;
}

/**
 * Generates language file with task titles
 */
function generateLang(name: string, NAME: string, tasks: CronTask[]): string {
  const langEntries = tasks
    .map(t => {
      return `    'LANG_${NAME}_TASK_${t.name.toUpperCase()}' => '${t.description ?? t.name}',`;
    })
    .join('\n');

  return `<?php
// InstantCMS 2. ${name} language file

return [
${langEntries}
];
`;
}

/**
 * Generates cron job files for an InstantCMS addon
 *
 * @param opts - Configuration options for the cron job
 * @returns Object containing generated files and metadata
 *
 * @example
 * ```typescript
 * const result = scaffoldCron({
 *   addon_name: 'my_component',
 *   tasks: [
 *     { name: 'cleanup', schedule: { minute: '0', hour: '*' }, action: 'taskCleanup' }
 *   ]
 * });
 * ```
 */
export function scaffoldCron(opts: ScaffoldCronOptions): ScaffoldResult {
  const { lowercase } = normalizeAddonName(opts.addon_name);
  const { UpperCamelCase } = normalizeAddonName(opts.addon_name);
  const uppercase = lowercase.toUpperCase();

  const files: Record<string, string> = {};
  const ctrl = `package/system/controllers/${lowercase}`;

  files[`${ctrl}/cron.php`] = generateCronMain(lowercase, UpperCamelCase, opts.tasks, opts.options);
  files[`${ctrl}/manifest.xml`] = generateManifest(lowercase, UpperCamelCase, opts.tasks);
  files[`package/system/languages/ru/controllers/${lowercase}/${lowercase}.php`] = generateLang(
    lowercase,
    uppercase,
    opts.tasks
  );

  return {
    addon_name: lowercase,
    tasks_count: opts.tasks.length,
    files,
    tasks: opts.tasks.map(t => ({
      name: t.name,
      schedule: formatSchedule(t.schedule),
      action: t.action,
      description: t.description,
    })),
  };
}
